### ISSUE TITLE
Expected colours for the different org babel blocks?

### ISSUE THREAD

**Issue by doolio** [fniessen/emacs-leuven-theme#45] opened 2017-05-14 14:03 UTC
For me, inside an org buffer an org babel quote block does not appear to have the expected background colour. There is also this (IMO ugly) trailing grey/blue line (see below) which takes up the last line inside the block.
 
![ob-quote-blk-leuven-theme](https://cloud.githubusercontent.com/assets/13859009/26034267/17f04d04-38b2-11e7-8843-359de80fb8d5.png)

I presume the following is the relevant line of emacs lisp. From this it appears to have the same background colour set as the generic org babel block colours (see screenshot further down) yet the above screenshot suggests that is not the case.

![ob-quote-blk-leuven-theme_1](https://cloud.githubusercontent.com/assets/13859009/26034270/1f7167fc-38b2-11e7-92bd-8ee690f16bc6.png)

Now if we consider the org babel example block it too does not appear to have the expected background colour. I have the following:

![ob-example-blk-leuven-theme](https://cloud.githubusercontent.com/assets/13859009/26034272/27214800-38b2-11e7-81e7-cd270d434668.png)

Yet, this following line of emacs lisp suggests I should see a different background colour to both a quote and src block.

![ob-example-blk-leuven-theme_1](https://cloud.githubusercontent.com/assets/13859009/26034273/2d34953a-38b2-11e7-9a3f-4cb5d8f13fe4.png)

I presume the following lines of emacs lisp define the generic org babel block colours.

![ob-blk-leuven-theme_1](https://cloud.githubusercontent.com/assets/13859009/26034275/37f95190-38b2-11e7-8c2f-33d1e4b1faa4.png)

For completeness this is how a src block appears:

![ob-src-blk-leuven-theme](https://cloud.githubusercontent.com/assets/13859009/26034278/3ce6bcce-38b2-11e7-855f-ad8ff44c69de.png)

Do these screenshots appear as you expect? 

Hopefully, you can make out the colours in the above screenshots. I've used `rainbow-mode` to fontify the colour values in the code. Thanks for `leuven` and your time.

**Comment by fniessen** [comment] 2017-05-16 19:22
Dear Doolio,

Regarding the quote, yes, it's not nice, but this is how it shows as well here. This is a problem which should be reported to the Org mode ML, IMHO.

Regarding the example, I do have the same look as yours. Doing `C-u C-x =` in there shows that org-example inherits from org-block... while, indeed, it's supposed to be different in my theme. Dunno ATM from where this "new" definition comes... I should investigate, but not much time right now.

Finally, the real src blocks look the same here as well. Sexy!

**Comment by jsigman** [comment] 2020-07-10 18:29
I'll piggyback on this: I am seeing the following for ob-ipython

Any idea if it's the same problem, or if it has a solution?

![Screen Shot 2020-07-10 at 2 23 34 PM](https://user-images.githubusercontent.com/2373529/87186608-c9498b80-c2b9-11ea-908e-2714c5a2f352.png)

**Comment by fniessen** [comment] 2020-11-10 20:31
Dear @doolio , did you report this to the Org mailing list?

**Comment by doolio** [comment] 2020-11-11 09:22
Hi Fabrice, I don't believe I did. I can do so if you like and point here so they can see the screenshots.

**Comment by fniessen** [comment] 2020-11-11 11:52
Dear @doolio , I think this could be worth it. Specify your Emacs and Org version.

**Comment by doolio** [comment] 2021-03-08 21:02
Fabrice, I've just submitted this bug to the [Org mode ML](https://lists.gnu.org/archive/html/emacs-orgmode/2021-03/msg00110.html). Apologies for taking so long to get around to this. Some good news perhaps is that the trailing grey/blue line is no longer present in the quote block. I've tested this on Emacs 26.2 and 27.1. Both with Org 9.4.4.

**Comment by fniessen** [comment] 2021-03-15 09:01
Would you still show (by testing other themes) that the problem is in Leuven-theme, please let me know.
Otherwise, currently, I'll close this request.

**Closed by fniessen** 2021-03-15 09:01 UTC
